title: RogueParsleyGraphics Portfolio
description: A creative portfolio website built with Jekyll and inspired by the Freelancer Theme.
baseurl: "" # the subpath of your site, e.g. /RogueParsleyGraphics
url: "https://yourusername.github.io" # update this with your GitHub Pages URL
